# Generated by Django 5.1.2 on 2024-10-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the contest", max_length=100
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The start time of the contest"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(help_text="The end time of the contest"),
                ),
                ("is_open", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the problem", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The description of the problem [Markdown]"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("SUPER_EASY", "Super Easy"),
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                            ("SUPER_HARD", "Super Hard"),
                        ],
                        help_text="The difficulty of the problem",
                        max_length=20,
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, help_text="Whether the problem is open"
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        help_text="The contest",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="judge.contest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField(help_text="The input of the problem")),
                (
                    "output",
                    models.TextField(help_text="Expected output of the problem"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.problem"
                    ),
                ),
            ],
        ),
    ]
