# Generated by Django 5.1.2 on 2024-12-11 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language",
            old_name="name",
            new_name="language",
        ),
    ]
