# Generated by Django 5.1.2 on 2024-12-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0002_rename_name_language_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the language for users",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(
                help_text="The name of the language in piston API.", max_length=100
            ),
        ),
    ]
