# Generated by Django 5.1.2 on 2024-10-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0002_testcase_case_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="case_no",
            field=models.PositiveIntegerField(help_text="The case number"),
        ),
    ]
