# Generated by Django 5.1.2 on 2024-10-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0003_alter_testcase_case_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Super Easy"),
                    (2, "Easy"),
                    (3, "Medium"),
                    (4, "Hard"),
                    (5, "SUPER_HARD"),
                ],
                help_text="The difficulty of the problem",
            ),
        ),
    ]
