# Generated by Django 5.1.4 on 2024-12-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0003_language_name_alter_language_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="difficulty",
        ),
        migrations.AlterField(
            model_name="problemsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("S", "Succeed"),
                    ("R", "Running"),
                    ("RE", "RuntimeError"),
                    ("ME", "Memory Limit Exceeded"),
                    ("TO", "Time Limit Exceeded"),
                    ("U", "Unmatched"),
                    ("E", "Error"),
                ],
                default="R",
                help_text="The status of the submission",
                max_length=2,
            ),
        ),
    ]
