# Generated by Django 5.1.2 on 2024-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0004_alter_problem_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "Super Easy"),
                    (2, "Easy"),
                    (3, "Medium"),
                    (4, "Hard"),
                    (5, "Super Hard"),
                ],
                help_text="The difficulty of the problem",
                max_length=20,
            ),
        ),
    ]
