# Generated by Django 5.1.2 on 2024-10-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0005_alter_problem_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="space_limit",
            field=models.IntegerField(
                default=64, help_text="The space limit of the problem (in megabytes)"
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="time_limit",
            field=models.IntegerField(
                default=2, help_text="The time limit of the problem (in seconds)"
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "Super Easy"),
                    (2, "Easy"),
                    (3, "Medium"),
                    (4, "Hard"),
                    (5, "Super Hard"),
                ],
                help_text="The difficulty of the problem",
            ),
        ),
    ]
