# Generated by Django 5.1.2 on 2024-10-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0007_alter_contest_is_open_alter_contest_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcasesubmission",
            name="success",
            field=models.BooleanField(
                default=False, help_text="Whether the test case is successful"
            ),
        ),
    ]
