# Generated by Django 5.1.2 on 2024-10-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0008_testcasesubmission_success"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="is_open",
        ),
        migrations.AddField(
            model_name="contest",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Whether the contest is public or not",
                verbose_name="Is the contest public?",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="status",
            field=models.CharField(
                choices=[("N", "Not Started"), ("R", "Running"), ("F", "Finished")],
                default="N",
                max_length=1,
            ),
        ),
    ]
