# Generated by Django 5.1.2 on 2024-10-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0009_remove_contest_is_open_contest_is_public_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="space_limit",
        ),
        migrations.AddField(
            model_name="problem",
            name="memory_limit",
            field=models.IntegerField(
                default=64, help_text="The memory limit of the problem (in megabytes)"
            ),
        ),
    ]
