# Generated by Django 5.1.2 on 2024-10-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0010_remove_problem_space_limit_problem_memory_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the language", max_length=100
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="",
                        help_text="The version of the language",
                        max_length=100,
                    ),
                ),
                (
                    "args",
                    models.CharField(
                        help_text="The arguments that are passed to the compiler/interpreter",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
