# Generated by Django 5.1.2 on 2024-10-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0011_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsubmission",
            name="language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="judge.language",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="args",
            field=models.CharField(
                blank=True,
                help_text="The arguments that are passed to the compiler/interpreter",
                max_length=100,
                null=True,
            ),
        ),
    ]
