# Generated by Django 5.1.2 on 2024-10-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0012_problemsubmission_language_alter_language_args"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemsubmission",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="judge.language"
            ),
        ),
    ]
