# Generated by Django 5.1.2 on 2024-10-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0013_alter_problemsubmission_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Whether the language is active"
            ),
        ),
    ]
