# Generated by Django 5.1.2 on 2024-10-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0014_language_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsubmission",
            name="user_solution",
            field=models.TextField(
                default="", help_text="The solution for this problem."
            ),
            preserve_default=False,
        ),
    ]
