# Generated by Django 5.1.2 on 2024-10-12 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0015_problemsubmission_user_solution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="judge.problem",
            ),
        ),
    ]
