# Generated by Django 5.1.2 on 2024-10-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0016_alter_testcase_problem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testcasesubmission",
            old_name="base_problem",
            new_name="base_submission",
        ),
    ]
