# Generated by Django 5.1.2 on 2024-10-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0017_rename_base_problem_testcasesubmission_base_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("S", "Succeed"),
                    ("R", "Running"),
                    ("RE", "RuntimeError"),
                    ("ME", "Memory Limit Exceeded"),
                    ("U", "Unmatched"),
                ],
                default="R",
                help_text="The status of the submission",
                max_length=2,
            ),
        ),
    ]
