# Generated by Django 5.1.2 on 2024-10-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0018_problemsubmission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("S", "Succeed"),
                    ("R", "Running"),
                    ("RE", "RuntimeError"),
                    ("ME", "Memory Limit Exceeded"),
                    ("U", "Unmatched"),
                    ("E", "Error"),
                ],
                default="R",
                help_text="The status of the submission",
                max_length=2,
            ),
        ),
    ]
