# Generated by Django 5.1.2 on 2024-10-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0019_alter_problemsubmission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcasesubmission",
            name="test",
            field=models.IntegerField(default=10),
        ),
    ]
