# Generated by Django 5.1.2 on 2024-10-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0020_testcasesubmission_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcasesubmission",
            name="test",
        ),
    ]
