# Generated by Django 5.1.2 on 2024-10-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0021_remove_testcasesubmission_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcasesubmission",
            name="base_submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_case_submissions",
                to="judge.problemsubmission",
            ),
        ),
    ]
