# Generated by Django 5.1.2 on 2024-10-12 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0022_alter_testcasesubmission_base_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsubmission",
            name="submitted_at",
            field=models.DateTimeField(
                auto_created=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
