# Generated by Django 5.1.2 on 2024-10-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0023_problemsubmission_submitted_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problemsubmission",
            options={"ordering": ("-id",)},
        ),
        migrations.AddField(
            model_name="problem",
            name="penalty_time",
            field=models.IntegerField(
                default=60, help_text="The penalty time of the problem (in seconds)"
            ),
        ),
    ]
