# Generated by Django 5.1.2 on 2024-10-14 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0024_alter_problemsubmission_options_problem_penalty_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemsubmission",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="judge.problem",
            ),
        ),
        migrations.AlterField(
            model_name="problemsubmission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="LeaderBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "penalty",
                    models.IntegerField(
                        default=0, help_text="The penalty time of the problem"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0, help_text="The score of the contest"
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.contest"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solved_problems",
                    models.ManyToManyField(blank=True, to="judge.problem"),
                ),
            ],
        ),
    ]
