# Generated by Django 5.1.2 on 2024-10-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0025_alter_problemsubmission_problem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaderboard",
            options={"ordering": ["-score", "penalty", "-id"]},
        ),
        migrations.RemoveField(
            model_name="contest",
            name="end_time",
        ),
        migrations.AddField(
            model_name="contest",
            name="duration",
            field=models.IntegerField(
                default=120, help_text="The duration of the contest (minutes)"
            ),
        ),
    ]
