# Generated by Django 5.1.2 on 2024-10-14 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0026_alter_leaderboard_options_remove_contest_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="status",
        ),
    ]
