# Generated by Django 5.1.2 on 2024-10-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0027_remove_contest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="is_public",
        ),
        migrations.AlterField(
            model_name="problem",
            name="penalty_time",
            field=models.IntegerField(
                default=1, help_text="The penalty time of the problem (in minutes)"
            ),
        ),
    ]
